### ISSUE TITLE
[FEATURE] #2 Home_view 퍼블리싱

### ISSUE THREAD

**Issue by hayounSong** [CDS-Seminar-1-IN-SOPT/Client#2]
## 🌴 작업 브랜치 
feat/home_view

## 💼 TASK 개요 

Home_view의 퍼블리싱 작업을 진행합니다.

## ✅ TODO 및 진행현황 

- [x] Home_view 퍼블리싱
- [ ] Homve_view 링크 연결 및 라우팅
- [x] Home_view API 모킹
