### ISSUE TITLE
[FEATURE] #5 Feed view 퍼블리싱, 기능구현

### ISSUE THREAD

**Issue by NamjunKim12** [CDS-Seminar-1-IN-SOPT/Client#5]
## 🌴 작업 브랜치 

`feat/#5`

## 💼 TASK 개요 

공연의 상세 페이지를 스타일링하고, 필요한 기능을 구현합니다. 

## ✅ TODO 및 진행현황 

- [ ] #6
- [ ] 컴포넌트 단위 및 구획 설정
- [ ] 컴포넌트별 마크업, 애니메이션 스타일링 구현
- [ ] 좋아요 누를시 숫자 증가 및 색상이 바뀌는 효과 구현
- [ ] 예매하기, 뒤로가기 버튼 및 쿠폰 발급 클릭 이벤트 생성
